### ISSUE TITLE
tag last version

### ISSUE THREAD

**Issue by andferrari** [tknopp/NFFT.jl#13]
thank you for this amazing package. 

It would be nice to tag commit [e5662f1](
https://github.com/tknopp/NFFT.jl/commit/e5662f1d07c1d092a6cb67b9934bd4b417a2300f) in order to
use `Pkg.add` in v0.4

**Comment by tknopp** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/4815

hope this is correctly tagged. 

Out of curious: Whats your use case?

**Comment by andferrari** [comment]
> Le 19 mars 2016 à 20:53, Tobias Knopp <notifications@github.com> a écrit :
> 
> JuliaLang/METADATA.jl#4815 <https://github.com/JuliaLang/METADATA.jl/pull/4815>
> hope this is correctly tagged.
> 
thanks !
> Out of curious: Whats your use case?
> 
Polychromatic image reconstruction in optical interferometry

See for example http://arxiv.org/abs/1503.01565 
where nfft.jl is mentioned.

**Comment by tknopp** [comment]
That is pretty cool!
This package is actually a toy project of mine. I wanted to test the performance of Julia and since I once coauthored parts of the NFFT C package I used the nfft as a use case. In the end I was pretty convinced and started to use Julia for most other projects I was working on.

Seeing someone actually using the package is very nice.

**Comment by tknopp** [comment]
new version is tagged
