### ISSUE TITLE
Input checking

### ISSUE THREAD

**Issue by robertdj** [tknopp/NFFT.jl#14]
Would it be of interest to check the input in some of the functions? E.g. if the size of the arrays match that of the NFFTPlan? If yes, I'll look into it.

**Comment by tknopp** [comment]
Good idea. Would be good to capsulate this into a `consistencyCheck` function that checks if the plan is consistent with the data. I have added you as a collaborator. Feel free to commit your stuff to master and do releases.
Thanks!

**Comment by robertdj** [comment]
Thanks for the collaborator access :-) 
Just want to make sure that that we're thinking about the same thing with a `consitencyCheck` function: I pushed to a [forked version](https://github.com/tknopp/NFFT.jl/compare/master...robertdj:master).

**Comment by tknopp** [comment]
In principle yes that how I thought it.
There are just two things:
 - I think using the `@assert` macro is not ideal here. Actually I am not sure how it is implemented in Julia. I would prefer raising an exception, which can be easily done by calling the `error` function you could write it like this
`!consistencyCheck && error("Data is not consistent with NFFTPlan")`

- But actually one could also pull the error into the consistency function since you then would not have to write all the error messages over and over

**Comment by robertdj** [comment]
I've grown fond of assertions, but I'll change it to exception raising. Good point about including the error in the `consistencyCheck`.

**Comment by tknopp** [comment]
Julia assertions or C assertions? Have you seen `@assert` in the wild in other packages or Base? I am not 100% sure here but using the error function seem to be a little bit more Julian to me.

I think the Julia assertion will in the end be a simple exception which makes it quite different to what happens in C

**Comment by robertdj** [comment]
Julia assertions. After your previous comment I've been searching around for `@assert` usage and it seems that it is not efficient -- as I unfortunately thought.

**Comment by tknopp** [comment]
Yes, the way assertions are used in C is not possible in Julia since one does not differentiate between compile time and runtime.
Exceptions are very expensive but that is not an issue because for our nfft functions the exception is never raised in "production use". It will always be a programming error and in that case we will get exceptions anyway but it will be a lot more unspecific since it will be an out of bounds exception if the sizes do not match.

**Comment by robertdj** [comment]
I've pushed an update with exceptions w/o `@assert`.

**Comment by tknopp** [comment]
thanks

**Comment by robertdj** [comment]
I just saw that the nightly version of Julia fails the test, whereas v0.4 succeeds. I only have v0.4.*, so I can't see how the test fails (besides the Travis log) -- is that possible for you?

**Comment by tknopp** [comment]
@robertdj: No I am still on Julia 0.4 and thus cannot track this down. There are some language changes in 0.5 that might need to be addressed

**Comment by robertdj** [comment]
I'll compile a nightly version and see what's going on.

**Comment by robertdj** [comment]
The problem is the recent introduction of `ReshapedArray` which is not an `Array`, but is an `AbstractArray`. 
In the test code for 2D and 3D the samples `x` are a reshaped `LinSpace`. It can be fixed by either allowing `AbstractArray`s in an `NFFTPlan` or by `collect`ing the samples in the test code.

I'm leaning towards the latter solution -- at least until `ReshapedArray`'s are documented.

**Comment by tknopp** [comment]
Yes, this seems to be the better solution for the moment. If we wanted to allow for `AbstractArray` nodes `x`, we would have to make the type of `x` a template parameter since otherwise, the `NFFTPlan` is not type stable anymore

**Comment by robertdj** [comment]
Good point! I've pushed a fix.

**Comment by tknopp** [comment]
thanks!
